### ISSUE TITLE
[Install error] The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by mrcnski** [LinusU/base32-encode#7]
```
$ yarn
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error base32-encode@2.0.0: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "15.11.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by LinusU** [comment]
As the error says, and as is detailed in [the 2.0.0 release notes & migration guide](https://github.com/LinusU/base32-encode/releases/tag/v2.0.0), your version of Node.js is unsupported:

> Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "15.11.0"

Node.js 15.x went out of support first of April this year, and stopped receiving security updates since first of July. Therefore this new version does no longer actively support them.

You can either use the `--ignore-engines` to your `yarn` command, or upgrade to Node.js 16.x which is supported.
