### ISSUE TITLE
[Runtime error] Cannot use import statement outside a module

### ISSUE THREAD

**Issue by mrcnski** [LinusU/base32-encode#8]
```
     /home/runner/work/skynet-js/skynet-js/node_modules/base32-encode/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import toDataView from 'to-data-view'
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import base32Decode from "base32-decode";
    > 2 | import base32Encode from "base32-encode";
        | ^
      3 | import { fromByteArray, toByteArray } from "base64-js";
      4 |
      5 | import { assertUint64 } from "./number";

      at Runtime.createScriptFromCode (../node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (utils/encoding.ts:2:1)
```

https://github.com/SkynetLabs/skynet-js/pull/227/checks?check_run_id=3160347860

**Comment by LinusU** [comment]
It's a bit interesting that Dependabot submits a normal PR for major/breaking changes without highighting that 😅 

Anyways, if you expand the release notes you'll see that it has a migration guide that tells you why it isn't working:

<img width="940" src="https://user-images.githubusercontent.com/189580/127155693-885d3ae2-1d43-4140-9ef4-d029a7097372.png">

It seems like your package, `skynet-js`, is currently building both for CommonJS and ESM? If you want to continue to support CommonJS you need to stay on version 1.x of this package.

Note that no new features have been added to 2.x (well, apart from the ESM switch), so you won't be missing out on anything by staying at 1.x. Also, if there is any security patches in the near future I'll backport them to 1.x as well.

That being said, I would recommend you to move to ESM only now that all actively supported versions of Node.js supports it.
If you want to do that, you can configure [TypeScript as shown here](https://stackoverflow.com/a/67371788/148072), and [read up on some general advice here.](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)

-----

Btw. the reason why your error is a bit confusing is because your source maps points it to `import base32Encode from "base32-encode";` line where you have been using `import` all the time. But I think that your transpiler is actually turning these `import` into `require`-calls. If not, I'd be happy to help you debug further!

**Comment by mrcnski** [comment]
Thanks for the detailed response, that was very helpful.

**Comment by LinusU** [comment]
No worries, good luck!
